server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE